### ISSUE TITLE
SIGSEGV during run

### ISSUE THREAD

**Issue by sbrodehl** [michaelchughes/KMeansRex#4]
Hi michael,

I just tried your k means (c++) implementation but only got a `SIGSEGV` :-(

It seems like Eigen is not able to assign the rows correctly during the initial sampling in [this line](https://github.com/michaelchughes/KMeansRex/blob/master/src/KMeansRexCore.cpp#L101).

My code looks just like this:

``` c++
Eigen::MatrixXd data = Eigen::MatrixXd::Random(100000, 2);
double* mu = 0;
double* z = 0;
RunKMeans(data.data(), data.rows(), data.cols(), 
          10, 15,
          42, "random",
          mu, z);
```

But the output is just a `SIGSEGV` with the latest version of Eigen.
Have you seen similar things? Otherwise I will dig into the problem a little bit more...

**Comment by michaelchughes** [comment]
This isn't an Eigen-related bug... this is simply due to the fact that mu and z in your example here are empty pointers and not valid pointers to arrays of the right size. When you call RunKMeans, it is expected that you hand off preallocated arrays of the right size:

mu : needs to be a pointer to an array of doubles of size K x D=data.cols()
z : needs to be a pointer to an array of doubles of size N=data.rows() 

See the newly-committed simple demo here for an example of successful usage:
https://github.com/michaelchughes/KMeansRex/blob/master/examples/simple_demo.cpp

**Comment by sbrodehl** [comment]
Oh, did not notice one need's preallocated arrays.
Thanks for the demo!

**Comment by michaelchughes** [comment]
Glad it makes sense now. Thanks again for your interest. Let me know of any future questions. Happy to help!
